# Add your OpenAI API key here
OPENAI_API_KEY = "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"

# To get your API key:
# 1. Go to https://platform.openai.com/account/api-keys
# 2. Create a new secret key
# 3. Replace "your-api-key-here" with your actual API key
# 4. Save the file